AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters: 
  PinpointApplicationId: 
    Type: String
    AllowedPattern: ^[0-9A-Za-z]+$
    Description: Pinpoint (Mobile Hub) Application ID.
    ConstraintDescription: Only alphanumeric characters allowed
    MaxLength: 250
    MinLength: 1
  PinpointEventName:
    Type: String
    Default: PinpointEvent
    Description: The name for custom events logged to Pinpoint analytics 
    MaxLength: 250
    MinLength: 1
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
  LambdaPutToPinpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          MOBILE_HUB_APPLICATION: !Ref PinpointApplicationId
          EVENT_NAME: !Ref PinpointEventName
      Policies:
        - PinpointEndpointAccessPolicy:
          PinpointApplicationId: !Ref PinpointApplicationId
        - MobileAnalyticsWriteOnlyAccessPolicy
      Events:
        SubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic